# Generated by Django 5.0.7 on 2024-10-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeders', '0002_alter_breed_code_alter_breeders_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.BigAutoField(auto_created=True, db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
