# Generated by Django 5.0.7 on 2024-11-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeders', '0003_alter_breed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='policyId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breed',
            name='txHash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
