# Generated by Django 5.0.7 on 2024-11-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeders', '0004_breed_policyid_breed_txhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='breeders',
            name='policyId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='breeders',
            name='txHash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
