# Generated by Django 5.0.7 on 2024-09-20 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chicks', '0012_alter_chicks_item'),
        ('customer', '0004_eggs_chicks_eggs_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('tracker_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('chick', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chick_tracker', to='chicks.chicks')),
                ('egg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egg_tracker', to='customer.eggs')),
            ],
        ),
    ]
