# Generated by Django 5.0.7 on 2024-09-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
