version: '3.8'

services:
  db:
    image: postgis/postgis
    env_file:
      - .env
    volumes:
      - poultry_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - cardano-network

  app:
    build: .
    env_file:
      - .env
    environment:
      - DB_ENGINE=${DB_ENGINE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: service_healthy

    command: >
     bash -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py seed_hrms &&
             python manage.py init_item_types &&
             python manage.py runserver 0.0.0.0:11000"
    ports:
      - 11000:11000
    restart: always
    volumes:
      - .:/app
    networks:
      - cardano-network

networks:
  cardano-network:
     driver: bridge

volumes:
  poultry_db_data:
