# Generated by Django 5.0.7 on 2024-08-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0002_chicks_egg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicks',
            name='number',
        ),
    ]
