# Generated by Django 5.0.7 on 2024-08-25 20:28

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0003_remove_chicks_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicks',
            name='chick_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='media/chicks_photos'),
        ),
    ]
