# Generated by Django 5.0.7 on 2024-08-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0006_alter_chicks_batchnumber'),
        ('hatchery', '0004_alter_candling_candlingcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chicks',
            name='egg',
        ),
        migrations.AddField(
            model_name='chicks',
            name='hatching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatching_chicks', to='hatchery.hatching'),
        ),
        migrations.AddField(
            model_name='chicks',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
