# Generated by Django 5.0.7 on 2024-09-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0010_remove_chicks_egg'),
        ('customer', '0004_eggs_chicks_eggs_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chicks',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chicks_customers', to='customer.customer'),
        ),
    ]
