# Generated by Django 5.0.7 on 2024-09-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicks', '0011_chicks_customer'),
        ('inventory', '0004_itemrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chicks',
            name='item',
            field=models.ForeignKey(blank=True, choices=[('customer', 'customer'), ('hatching', 'hatching')], default='customer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
