# Generated by Django 5.0.7 on 2024-08-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0003_alter_eggsetting_settingcode_alter_hatchery_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candling',
            name='candlingcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hatching',
            name='hatchingcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='incubation',
            name='incubationcode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
