# Generated by Django 5.0.7 on 2024-08-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0005_incubators_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubators',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
