# Generated by Django 5.0.7 on 2024-08-30 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_eggs_item'),
        ('hatchery', '0006_incubators_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsetting',
            name='egg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.eggs'),
        ),
    ]
