# Generated by Django 5.0.7 on 2024-09-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0007_eggsetting_egg'),
        ('inventory', '0004_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsetting',
            name='item_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemrequest'),
        ),
    ]
