# Generated by Django 5.0.7 on 2024-09-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0008_eggsetting_item_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggsetting',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
