# Generated by Django 5.0.7 on 2024-09-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0009_eggsetting_is_approved'),
        ('inventory', '0004_itemrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggsetting',
            name='item_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_setting', to='inventory.itemrequest'),
        ),
    ]
