# Generated by Django 5.0.7 on 2024-11-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0012_eggsetting_txhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='incubation',
            name='txHash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
