# Generated by Django 5.0.7 on 2025-03-18 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0015_hatching_txhash'),
        ('inventory', '0006_itemrequest_txhash'),
        ('vendor', '0003_remove_feeds_vendorcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('settingcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('chicks', models.CharField(blank=True, max_length=50, null=True)),
                ('feeds', models.IntegerField(blank=True, max_length=50, null=True)),
                ('available_quantity', models.IntegerField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('txHash', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.feeds')),
                ('item_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_setting', to='inventory.itemrequest')),
            ],
            options={
                'verbose_name': 'feedSetting',
                'verbose_name_plural': 'feedSettings',
                'db_table': 'feedsetting',
                'ordering': ['created'],
                'managed': True,
            },
        ),
    ]
