# Generated by Django 5.0.7 on 2025-03-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0016_feedsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsetting',
            name='chicks',
        ),
    ]
