# Generated by Django 5.0.7 on 2025-03-19 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0017_remove_feedsetting_chicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedingcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('chicks', models.IntegerField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=50, null=True)),
                ('txHash', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feedsetting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_feedsetting', to='hatchery.feedsetting')),
            ],
            options={
                'verbose_name': 'Feedings',
                'verbose_name_plural': 'Feedings',
                'db_table': 'Feedings',
                'ordering': ['created'],
                'managed': True,
            },
        ),
    ]
