# Generated by Django 5.0.7 on 2025-04-18 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0018_feedings'),
        ('inventory', '0006_itemrequest_txhash'),
        ('vendor', '0005_alter_medicine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('settingcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('medicines', models.IntegerField(blank=True, max_length=50, null=True)),
                ('available_quantity', models.IntegerField(blank=True, max_length=50, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('txHash', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicine_setting', to='inventory.itemrequest')),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor.medicineinventory')),
            ],
            options={
                'verbose_name': 'MedicineSetting',
                'verbose_name_plural': 'MedicineSettings',
                'db_table': 'medicinesetting',
                'ordering': ['created'],
                'managed': True,
            },
        ),
    ]
