# Generated by Django 5.0.7 on 2025-04-18 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hatchery', '0019_medicinesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicationcode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('chicks', models.IntegerField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, max_length=50, null=True)),
                ('txHash', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('medicinesetting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_feedsetting', to='hatchery.medicinesetting')),
            ],
            options={
                'verbose_name': 'medications',
                'verbose_name_plural': 'medications',
                'db_table': 'medications',
                'ordering': ['created'],
                'managed': True,
            },
        ),
    ]
