# Generated by Django 5.0.7 on 2024-08-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='related_object',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
