# Generated by Django 5.0.7 on 2024-11-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='policyId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='txHash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
