# Generated by Django 5.0.7 on 2024-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eggs',
            name='batchnumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
