# Generated by Django 5.0.7 on 2024-09-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_eggs_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='eggs',
            name='chicks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='eggs',
            name='source',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('farm', 'farm')], default='customer', max_length=50, null=True),
        ),
    ]
