# Generated by Django 5.0.7 on 2024-08-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='supervisor',
        ),
    ]
