# Generated by Django 5.0.7 on 2024-09-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('human_resource', '0002_remove_employee_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.usersettings'),
        ),
    ]
