# Generated by Django 5.0.7 on 2024-09-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0003_alter_employee_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
    ]
