# Generated by Django 5.0.7 on 2024-10-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0004_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='department',
        ),
    ]
